# Generated by Django 5.0.6 on 2024-05-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='last_play',
            field=models.DateField(),
        ),
    ]
